#!/usr/bin/env python3
#
# Copyright (c) 2025 Huawei Technologies Co., Ltd. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file is a part of the triton-ascend project.
#
"""
Sphinx gettext translation workflow for Chinese docs.

This script follows the standard Sphinx gettext i18n workflow:
  1. Run sphinx-build -b gettext to generate .pot files from docs/zh/
  2. Parse .pot files, compare with existing .po files (translation memory)
  3. Translate new/changed entries via DeepSeek API
  4. Save .po files to locale/en/LC_MESSAGES/
  5. (Sphinx build -D language=en will use .po files to render English HTML)

Directory layout:
    docs/zh/            Chinese source Markdown/RST files (input)
    locale/zh/LC_MESSAGES/   .pot template files (generated by sphinx-build -b gettext)
    locale/en/LC_MESSAGES/   .po translation files (generated by this script)

Usage:
    # Translate all .pot files that have new/changed content
    python translate_md.py --all

    # Translate specific .pot files
    python translate_md.py --files "quick_start.pot,FAQ.pot"
"""

import argparse
import asyncio
import hashlib
import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path
from typing import Optional

from openai import AsyncOpenAI

# --- Directory Layout ---
ZH_DIR = Path("docs/zh")
LOCALE_DIR = Path("locale")
POT_DIR = LOCALE_DIR / "zh" / "LC_MESSAGES"
PO_DIR = LOCALE_DIR / "en" / "LC_MESSAGES"

SYSTEM_PROMPT = ("You are a professional technical documentation translation expert, "
                 "proficient in Chinese-to-English technical document translation.")

BLOCK_TRANSLATION_PROMPT = """Translate the following Chinese text into English.

Rules:
1. Return ONLY the translated text, no explanations, no markdown fences.
2. Use standard English technical terminology.
3. For proper nouns (person names, company names, product names), keep them as-is.
4. If the text contains inline code (`code`), leave the inline code content unchanged.
5. If any sentence is too difficult to translate, keep the original Chinese as-is.

Text to translate:
{content}"""

# ---------------------------------------------------------------------------
# PO / POT file parsing
# ---------------------------------------------------------------------------


def parse_pot_file(filepath: Path) -> dict:
    """
    Parse a .pot or .po file and return entries dict.

    Returns dict mapping msgid -> entry dict:
    {
        "msgid": str,
        "msgstr": str,
        "translated": bool,
        "locations": list[str],   # source file locations
    }
    """
    entries = {}
    if not filepath.exists():
        return entries

    raw = filepath.read_text(encoding="utf-8")

    # Split into entry blocks separated by blank lines
    blocks = raw.split('\n\n')

    for block in blocks:
        block = block.strip()
        if not block:
            continue

        # Skip header entry (msgid "" at start)
        if block.startswith('msgid ""') and '# ' not in block.split('\n')[0]:
            continue

        msgid = _extract_po_value(block, 'msgid')
        msgstr = _extract_po_value(block, 'msgstr')
        locations = _extract_locations(block)

        if msgid is not None:
            entries[msgid] = {
                "msgid": msgid,
                "msgstr": msgstr or "",
                "translated": bool(msgstr and msgstr.strip()),
                "locations": locations,
            }

    return entries


def _extract_po_value(block: str, field: str) -> Optional[str]:
    """Extract the value of a msgid/msgstr field from a PO block."""
    pattern = re.compile(
        rf'{field}\s+"((?:[^"\\]|\\.)*)"',
        re.MULTILINE,
    )
    match = pattern.search(block)
    if match:
        raw = match.group(1)
        return raw.replace('\\"', '"').replace('\\\\', '\\')

    # Multi-line variant
    if f'{field} ""' in block:
        # Collect all following "...\n" lines
        lines = block.split('\n')
        in_field = False
        parts = []
        for line in lines:
            if line.startswith(f'{field} ""'):
                in_field = True
                continue
            if in_field:
                # Match "content"
                m = re.match(r'\s*"((?:[^"\\]|\\.)*)"', line)
                if m:
                    parts.append(m.group(1).replace('\\"', '"').replace('\\\\', '\\'))
                else:
                    break
        if parts:
            return ''.join(parts)
        return ""

    return None


def _extract_locations(block: str) -> list[str]:
    """Extract file:line locations from a PO block."""
    locs = []
    for line in block.split('\n'):
        if line.startswith('#:'):
            locs.extend(line[2:].strip().split())
    return locs


def _is_excluded_location(location: str, excluded_dirs: list[str]) -> bool:
    """Check if a file location belongs to an excluded directory."""
    for d in excluded_dirs:
        if f"/{d}/" in location or location.startswith(f"{d}/"):
            return True
    return False


def write_po_file(filepath: Path, entries: dict, source_pot: str = ""):
    """Write entries dict to a .po file."""
    filepath.parent.mkdir(parents=True, exist_ok=True)

    now_str = time.strftime("%Y-%m-%d %H:%M%z")

    lines = []
    # Header
    lines.append(f'# English translations for triton-ascend docs.\n'
                 f'# Copyright (c) 2025 Huawei Technologies Co., Ltd.\n'
                 f'#\n'
                 f'msgid ""\n'
                 f'msgstr ""\n'
                 f'"Project-Id-Version: triton-ascend-docs\\n"\n'
                 f'"POT-Creation-Date: {now_str}\\n"\n'
                 f'"PO-Revision-Date: {now_str}\\n"\n'
                 f'"Last-Translator: Auto Translation (DeepSeek)\\n"\n'
                 f'"Language-Team: English\\n"\n'
                 f'"Language: en\\n"\n'
                 f'"MIME-Version: 1.0\\n"\n'
                 f'"Content-Type: text/plain; charset=UTF-8\\n"\n'
                 f'"Content-Transfer-Encoding: 8bit\\n"\n'
                 f'"Plural-Forms: nplurals=2; plural=(n != 1);\\n"\n')

    for entry in entries.values():
        msgid = entry["msgid"]
        msgstr = entry.get("msgstr", "")

        # Locations
        for loc in entry.get("locations", []):
            lines.append(f'#: {loc}')

        # Write msgid
        if '\n' in msgid:
            lines.append('msgid ""')
            for part in msgid.split('\n'):
                escaped = _escape_po(part)
                lines.append(f'"{escaped}\\n"')
        else:
            lines.append(f'msgid "{_escape_po(msgid)}"')

        # Write msgstr
        if '\n' in msgstr:
            lines.append('msgstr ""')
            for part in msgstr.split('\n'):
                escaped = _escape_po(part)
                lines.append(f'"{escaped}\\n"')
        else:
            lines.append(f'msgstr "{_escape_po(msgstr)}"')

        lines.append('')  # blank line separator

    text = '\n'.join(lines)
    filepath.write_text(text, encoding="utf-8")


def _escape_po(s: str) -> str:
    """Escape a string for PO format."""
    s = s.replace('\\', '\\\\')
    s = s.replace('"', '\\"')
    return s


# ---------------------------------------------------------------------------
# Translation engine
# ---------------------------------------------------------------------------


class PoTranslator:
    """Translate .pot entries to .po using DeepSeek API with translation memory."""

    def __init__(self, api_key: str):
        self.client = AsyncOpenAI(api_key=api_key, base_url="https://api.deepseek.com")

    async def translate_file(self, pot_path: Path) -> bool:
        """Translate a single .pot file, producing/updating the matching .po file."""
        rel = pot_path.relative_to(POT_DIR)
        po_path = PO_DIR / rel
        if po_path.suffix != '.po':
            po_path = po_path.with_suffix('.po')

        # Parse existing translations (if any)
        pot_entries = parse_pot_file(pot_path)
        po_entries = parse_pot_file(po_path)

        if not pot_entries:
            print(f"  Skip: {pot_path.name} (empty)")
            return False

        name = pot_path.stem
        print(f"  {name}: {len(pot_entries)} entries", end=" ", flush=True)

        # Determine which entries need translation
        new_entries = {}
        untranslated = []
        translations_kept = 0

        for msgid, entry in pot_entries.items():
            existing = po_entries.get(msgid)
            if existing and existing.get("translated"):
                # Translation memory hit - keep it
                new_entries[msgid] = existing
                translations_kept += 1
            else:
                # New or changed entry - needs translation
                new_entry = {
                    "msgid": msgid,
                    "msgstr": "",
                    "translated": False,
                    "locations": entry.get("locations", []),
                }
                new_entries[msgid] = new_entry
                untranslated.append((msgid, msgid))

        print(f"[{translations_kept} kept, {len(untranslated)} new]", end=" ", flush=True)

        # Translate new entries via API
        if untranslated:
            print(f"\n    Translating {len(untranslated)} entry(ies)...", end=" ", flush=True)
            for idx, (msgid, text) in enumerate(untranslated):
                translation = await self._translate_single(text, name)
                if translation:
                    new_entries[msgid]["msgstr"] = translation
                    new_entries[msgid]["translated"] = True
                if idx < len(untranslated) - 1:
                    await asyncio.sleep(0.3)
            print(" done", end=" ", flush=True)

        # Write .po file
        write_po_file(po_path, new_entries, str(pot_path))
        print("OK")
        return True

    async def _translate_single(self, content: str, context: str = "") -> Optional[str]:
        """Translate a single text string via DeepSeek API."""
        prompt = BLOCK_TRANSLATION_PROMPT.format(content=content)
        system = SYSTEM_PROMPT
        if context:
            system = f"{SYSTEM_PROMPT} (File: {context})"

        try:
            response = await self.client.chat.completions.create(
                model="deepseek-chat",
                messages=[
                    {"role": "system", "content": system},
                    {"role": "user", "content": prompt},
                ],
                max_tokens=8192,
                temperature=0.3,
            )
            text = response.choices[0].message.content
            return text.strip() if text else None
        except Exception as e:
            print(f"API error: {e}")
            return None

    async def translate_files(self, pot_list: list[Path], output_json: str) -> int:
        """Translate a list of .pot files sequentially."""
        print(f"Translating {len(pot_list)} .pot file(s)")

        success_files = []
        for pot_path in pot_list:
            ok = await self.translate_file(pot_path)
            if ok:
                rel = pot_path.relative_to(POT_DIR)
                po_path = PO_DIR / rel
                if po_path.suffix != '.po':
                    po_path = po_path.with_suffix('.po')
                success_files.append(str(po_path))

        print(f"\nResult: {len(success_files)}/{len(pot_list)} translated")

        report = {
            "success_files": success_files,
            "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
            "total_files": len(pot_list),
            "success_count": len(success_files),
        }
        out = Path(output_json)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"Results written to {output_json}")

        return 0 if success_files else 1


# ---------------------------------------------------------------------------
# POT discovery helpers
# ---------------------------------------------------------------------------

EXCLUDED_DIRS = ["python-api", "triton_api", "triton_api_extension", "libdevice"]


def _is_excluded(pot_path: Path) -> bool:
    """Check if a .pot file path falls under an excluded source directory."""
    try:
        rel = pot_path.relative_to(POT_DIR)
    except ValueError:
        return False
    # Check locations via the pot file content
    entries = parse_pot_file(pot_path)
    for entry in entries.values():
        for loc in entry.get("locations", []):
            if _is_excluded_location(loc, EXCLUDED_DIRS):
                return True
    return False


def find_all_pot_files() -> list[Path]:
    """Find all .pot files in locale/zh/LC_MESSAGES/ excluding those from excluded dirs."""
    result = []
    for pot_file in sorted(POT_DIR.rglob("*.pot")):
        if not _is_excluded(pot_file):
            result.append(pot_file)
    return result


def find_changed_pot_files() -> list[Path]:
    """Find .pot files that have new/changed entries compared to their .po counterpart.

    Uses git diff on .pot files if available (to detect which .pot files were regenerated),
    otherwise compares .pot and .po entry hashes directly.
    """
    # Try git diff first
    try:
        result = subprocess.run(
            ["git", "diff", "--name-only", "--diff-filter=ACMUX", "HEAD", "--", "locale/zh/LC_MESSAGES/"],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode == 0 and result.stdout.strip():
            changed_pots = []
            for line in result.stdout.strip().split("\n"):
                line = line.strip()
                if line.endswith(".pot"):
                    p = Path(line)
                    if not _is_excluded(p):
                        changed_pots.append(p)
            if changed_pots:
                return changed_pots
    except Exception:
        pass

    # Fallback: compare .pot entries with .po entries
    changed = []
    for pot_file in POT_DIR.rglob("*.pot"):
        if _is_excluded(pot_file):
            continue

        rel = pot_file.relative_to(POT_DIR)
        po_file = PO_DIR / rel
        if po_file.suffix != '.po':
            po_file = po_file.with_suffix('.po')

        pot_entries = parse_pot_file(pot_file)
        po_entries = parse_pot_file(po_file)

        # Check if any pot entry is missing or different in po
        for msgid, entry in pot_entries.items():
            existing = po_entries.get(msgid)
            if not existing or not existing.get("translated"):
                changed.append(pot_file)
                break

    return changed


def run_sphinx_gettext():
    """Run sphinx-build -b gettext to generate/update .pot files."""
    print("Running: sphinx-build -b gettext docs/zh locale/")
    result = subprocess.run(
        [sys.executable, "-m", "sphinx", "-b", "gettext", "-q",
         str(ZH_DIR), str(LOCALE_DIR)],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"sphinx-build failed:\n{result.stderr}")
        return False
    if result.stderr:
        print(f"  stderr: {result.stderr.strip()}")
    print("  Done")
    return True


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def write_empty_json(output_json: str, reason: str = ""):
    report = {
        "success_files": [],
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "total_files": 0,
        "success_count": 0,
        "note": reason,
    }
    out = Path(output_json)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")


async def async_main():
    parser = argparse.ArgumentParser(description="Sphinx gettext translation: docs/zh/ → locale/en/LC_MESSAGES/")
    parser.add_argument("--files", help="Comma-separated .pot file names (relative to locale/zh/LC_MESSAGES/)")
    parser.add_argument("--all", action="store_true", help="Translate all .pot files")
    parser.add_argument("--first-time", action="store_true",
                        help="First-time: run sphinx-build + translate ALL .pot files")
    parser.add_argument("--skip-gettext", action="store_true",
                        help="Skip sphinx-build -b gettext step (use existing .pot files)")
    parser.add_argument("--output-json", default=os.getenv("OUTPUT_JSON", "/tmp/translation_results.json"))
    parser.add_argument("--api-key", default=os.getenv("DEEPSEEK_API_KEY"))
    args = parser.parse_args()

    output_json = args.output_json

    api_key = args.api_key or os.getenv("DEEPSEEK_API_KEY")
    if not api_key:
        msg = "DEEPSEEK_API_KEY not set"
        print(f"Error: {msg}")
        write_empty_json(output_json, msg)
        return 1

    # Step 1: Generate .pot files via sphinx-build (unless --skip-gettext)
    if not args.skip_gettext:
        if not run_sphinx_gettext():
            write_empty_json(output_json, "sphinx-build -b gettext failed")
            return 1

    # Step 2: Determine which .pot files to translate
    if args.files:
        raw_files = [f.strip() for f in args.files.split(",") if f.strip()]
        pot_list = []
        for f in raw_files:
            p = Path(f)
            if not p.exists():
                p = POT_DIR / f
            if p.exists() and p.suffix == ".pot":
                if not _is_excluded(p):
                    pot_list.append(p)
    elif args.first_time:
        pot_list = find_all_pot_files()
        print(f"First-time translation: found {len(pot_list)} .pot file(s)")
    elif args.all:
        pot_list = find_changed_pot_files()
        print(f"Incremental translation: found {len(pot_list)} changed .pot file(s)")
    else:
        msg = "specify --files, --all, or --first-time"
        print(f"Error: {msg}")
        write_empty_json(output_json, msg)
        return 1

    if not pot_list:
        print("No .pot files to translate")
        write_empty_json(output_json, "no .pot files to translate")
        return 0

    translator = PoTranslator(api_key=api_key)
    return await translator.translate_files(pot_list, output_json)


if __name__ == "__main__":
    sys.exit(asyncio.run(async_main()))
